language: python
python:
  - "3.7"

cache: pip

# command to install dependencies
install: pip install -r requirements.txt


# command to run tests
script:
  #- nosetests --with-coverage --cover-package=app
  py.test --cov=app

after_success: coveralls
