"""empty message

Revision ID: f8fccc456d97
Revises: 2af64018138c
Create Date: 2017-08-28 23:25:25.190926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fccc456d97'
down_revision = '2af64018138c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('bucketlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucketlist_id'], ['bucketlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bucketlist_items_title'), 'bucketlist_items', ['title'], unique=True)
    op.alter_column('bucketlists', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_bucketlists_title'), 'bucketlists', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bucketlists_title'), table_name='bucketlists')
    op.alter_column('bucketlists', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_bucketlist_items_title'), table_name='bucketlist_items')
    op.drop_table('bucketlist_items')
    # ### end Alembic commands ###
